// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: datanode.proto

package datanode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vc            map[string]int64       `protobuf:"bytes,1,rep,name=vc,proto3" json:"vc,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_datanode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_datanode_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClock) GetVc() map[string]int64 {
	if x != nil {
		return x.Vc
	}
	return nil
}

type FlightState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                     // Ejemplo: "A Tiempo", "Retrasado", "Cancelado"
	Gate          string                 `protobuf:"bytes,3,opt,name=gate,proto3" json:"gate,omitempty"`                                         // Puerta de embarque asignada
	ScheduledTime int64                  `protobuf:"varint,4,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"` // Hora programada (timestamp)
	Clock         *VectorClock           `protobuf:"bytes,5,opt,name=clock,proto3" json:"clock,omitempty"`                                       // Reloj Vectorial asociado a este estado
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightState) Reset() {
	*x = FlightState{}
	mi := &file_datanode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightState) ProtoMessage() {}

func (x *FlightState) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightState.ProtoReflect.Descriptor instead.
func (*FlightState) Descriptor() ([]byte, []int) {
	return file_datanode_proto_rawDescGZIP(), []int{1}
}

func (x *FlightState) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *FlightState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FlightState) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *FlightState) GetScheduledTime() int64 {
	if x != nil {
		return x.ScheduledTime
	}
	return 0
}

func (x *FlightState) GetClock() *VectorClock {
	if x != nil {
		return x.Clock
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *FlightState           `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"` // El nuevo estado del vuelo con su VC adjunto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_datanode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_datanode_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetUpdate() *FlightState {
	if x != nil {
		return x.Update
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Mensaje de éxito, o si hubo un conflicto resuelto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_datanode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_datanode_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	ClientVersion *VectorClock           `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_datanode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_datanode_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *ReadRequest) GetClientVersion() *VectorClock {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentState  *FlightState           `protobuf:"bytes,1,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"` // El estado actual del vuelo, incluyendo su VC
	Consistent    bool                   `protobuf:"varint,2,opt,name=consistent,proto3" json:"consistent,omitempty"`                        // Indica si la respuesta cumple con la versión solicitada (Monotonic)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_datanode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_datanode_proto_rawDescGZIP(), []int{5}
}

func (x *ReadResponse) GetCurrentState() *FlightState {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

func (x *ReadResponse) GetConsistent() bool {
	if x != nil {
		return x.Consistent
	}
	return false
}

type GossipRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SenderId      string                  `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Updates       map[string]*FlightState `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_datanode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_datanode_proto_rawDescGZIP(), []int{6}
}

func (x *GossipRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *GossipRequest) GetUpdates() map[string]*FlightState {
	if x != nil {
		return x.Updates
	}
	return nil
}

type GossipResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Success        bool                    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CounterUpdates map[string]*FlightState `protobuf:"bytes,2,rep,name=counter_updates,json=counterUpdates,proto3" json:"counter_updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_datanode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_datanode_proto_rawDescGZIP(), []int{7}
}

func (x *GossipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GossipResponse) GetCounterUpdates() map[string]*FlightState {
	if x != nil {
		return x.CounterUpdates
	}
	return nil
}

var File_datanode_proto protoreflect.FileDescriptor

const file_datanode_proto_rawDesc = "" +
	"\n" +
	"\x0edatanode.proto\x12\bdatanode\"s\n" +
	"\vVectorClock\x12-\n" +
	"\x02vc\x18\x01 \x03(\v2\x1d.datanode.VectorClock.VcEntryR\x02vc\x1a5\n" +
	"\aVcEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xaa\x01\n" +
	"\vFlightState\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04gate\x18\x03 \x01(\tR\x04gate\x12%\n" +
	"\x0escheduled_time\x18\x04 \x01(\x03R\rscheduledTime\x12+\n" +
	"\x05clock\x18\x05 \x01(\v2\x15.datanode.VectorClockR\x05clock\">\n" +
	"\rUpdateRequest\x12-\n" +
	"\x06update\x18\x01 \x01(\v2\x15.datanode.FlightStateR\x06update\"D\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"h\n" +
	"\vReadRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12<\n" +
	"\x0eclient_version\x18\x02 \x01(\v2\x15.datanode.VectorClockR\rclientVersion\"j\n" +
	"\fReadResponse\x12:\n" +
	"\rcurrent_state\x18\x01 \x01(\v2\x15.datanode.FlightStateR\fcurrentState\x12\x1e\n" +
	"\n" +
	"consistent\x18\x02 \x01(\bR\n" +
	"consistent\"\xbf\x01\n" +
	"\rGossipRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12>\n" +
	"\aupdates\x18\x02 \x03(\v2$.datanode.GossipRequest.UpdatesEntryR\aupdates\x1aQ\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.datanode.FlightStateR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x0eGossipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12U\n" +
	"\x0fcounter_updates\x18\x02 \x03(\v2,.datanode.GossipResponse.CounterUpdatesEntryR\x0ecounterUpdates\x1aX\n" +
	"\x13CounterUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.datanode.FlightStateR\x05value:\x028\x012\xdc\x01\n" +
	"\x0fDatanodeService\x12B\n" +
	"\rProcessUpdate\x12\x17.datanode.UpdateRequest\x1a\x18.datanode.UpdateResponse\x12@\n" +
	"\x0fReadFlightState\x12\x15.datanode.ReadRequest\x1a\x16.datanode.ReadResponse\x12C\n" +
	"\x0eExchangeGossip\x12\x17.datanode.GossipRequest\x1a\x18.datanode.GossipResponseB\x19Z\x17aeroDist/proto/datanodeb\x06proto3"

var (
	file_datanode_proto_rawDescOnce sync.Once
	file_datanode_proto_rawDescData []byte
)

func file_datanode_proto_rawDescGZIP() []byte {
	file_datanode_proto_rawDescOnce.Do(func() {
		file_datanode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datanode_proto_rawDesc), len(file_datanode_proto_rawDesc)))
	})
	return file_datanode_proto_rawDescData
}

var file_datanode_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_datanode_proto_goTypes = []any{
	(*VectorClock)(nil),    // 0: datanode.VectorClock
	(*FlightState)(nil),    // 1: datanode.FlightState
	(*UpdateRequest)(nil),  // 2: datanode.UpdateRequest
	(*UpdateResponse)(nil), // 3: datanode.UpdateResponse
	(*ReadRequest)(nil),    // 4: datanode.ReadRequest
	(*ReadResponse)(nil),   // 5: datanode.ReadResponse
	(*GossipRequest)(nil),  // 6: datanode.GossipRequest
	(*GossipResponse)(nil), // 7: datanode.GossipResponse
	nil,                    // 8: datanode.VectorClock.VcEntry
	nil,                    // 9: datanode.GossipRequest.UpdatesEntry
	nil,                    // 10: datanode.GossipResponse.CounterUpdatesEntry
}
var file_datanode_proto_depIdxs = []int32{
	8,  // 0: datanode.VectorClock.vc:type_name -> datanode.VectorClock.VcEntry
	0,  // 1: datanode.FlightState.clock:type_name -> datanode.VectorClock
	1,  // 2: datanode.UpdateRequest.update:type_name -> datanode.FlightState
	0,  // 3: datanode.ReadRequest.client_version:type_name -> datanode.VectorClock
	1,  // 4: datanode.ReadResponse.current_state:type_name -> datanode.FlightState
	9,  // 5: datanode.GossipRequest.updates:type_name -> datanode.GossipRequest.UpdatesEntry
	10, // 6: datanode.GossipResponse.counter_updates:type_name -> datanode.GossipResponse.CounterUpdatesEntry
	1,  // 7: datanode.GossipRequest.UpdatesEntry.value:type_name -> datanode.FlightState
	1,  // 8: datanode.GossipResponse.CounterUpdatesEntry.value:type_name -> datanode.FlightState
	2,  // 9: datanode.DatanodeService.ProcessUpdate:input_type -> datanode.UpdateRequest
	4,  // 10: datanode.DatanodeService.ReadFlightState:input_type -> datanode.ReadRequest
	6,  // 11: datanode.DatanodeService.ExchangeGossip:input_type -> datanode.GossipRequest
	3,  // 12: datanode.DatanodeService.ProcessUpdate:output_type -> datanode.UpdateResponse
	5,  // 13: datanode.DatanodeService.ReadFlightState:output_type -> datanode.ReadResponse
	7,  // 14: datanode.DatanodeService.ExchangeGossip:output_type -> datanode.GossipResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_datanode_proto_init() }
func file_datanode_proto_init() {
	if File_datanode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datanode_proto_rawDesc), len(file_datanode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datanode_proto_goTypes,
		DependencyIndexes: file_datanode_proto_depIdxs,
		MessageInfos:      file_datanode_proto_msgTypes,
	}.Build()
	File_datanode_proto = out.File
	file_datanode_proto_goTypes = nil
	file_datanode_proto_depIdxs = nil
}
