// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: datanode.proto

package datanode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatanodeService_ProcessUpdate_FullMethodName   = "/datanode.DatanodeService/ProcessUpdate"
	DatanodeService_ReadFlightState_FullMethodName = "/datanode.DatanodeService/ReadFlightState"
	DatanodeService_ExchangeGossip_FullMethodName  = "/datanode.DatanodeService/ExchangeGossip"
)

// DatanodeServiceClient is the client API for DatanodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatanodeServiceClient interface {
	ProcessUpdate(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	ReadFlightState(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	ExchangeGossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error)
}

type datanodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatanodeServiceClient(cc grpc.ClientConnInterface) DatanodeServiceClient {
	return &datanodeServiceClient{cc}
}

func (c *datanodeServiceClient) ProcessUpdate(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, DatanodeService_ProcessUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) ReadFlightState(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, DatanodeService_ReadFlightState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) ExchangeGossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipResponse)
	err := c.cc.Invoke(ctx, DatanodeService_ExchangeGossip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatanodeServiceServer is the server API for DatanodeService service.
// All implementations must embed UnimplementedDatanodeServiceServer
// for forward compatibility.
type DatanodeServiceServer interface {
	ProcessUpdate(context.Context, *UpdateRequest) (*UpdateResponse, error)
	ReadFlightState(context.Context, *ReadRequest) (*ReadResponse, error)
	ExchangeGossip(context.Context, *GossipRequest) (*GossipResponse, error)
	mustEmbedUnimplementedDatanodeServiceServer()
}

// UnimplementedDatanodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatanodeServiceServer struct{}

func (UnimplementedDatanodeServiceServer) ProcessUpdate(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessUpdate not implemented")
}
func (UnimplementedDatanodeServiceServer) ReadFlightState(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFlightState not implemented")
}
func (UnimplementedDatanodeServiceServer) ExchangeGossip(context.Context, *GossipRequest) (*GossipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeGossip not implemented")
}
func (UnimplementedDatanodeServiceServer) mustEmbedUnimplementedDatanodeServiceServer() {}
func (UnimplementedDatanodeServiceServer) testEmbeddedByValue()                         {}

// UnsafeDatanodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatanodeServiceServer will
// result in compilation errors.
type UnsafeDatanodeServiceServer interface {
	mustEmbedUnimplementedDatanodeServiceServer()
}

func RegisterDatanodeServiceServer(s grpc.ServiceRegistrar, srv DatanodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedDatanodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatanodeService_ServiceDesc, srv)
}

func _DatanodeService_ProcessUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).ProcessUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_ProcessUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).ProcessUpdate(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_ReadFlightState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).ReadFlightState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_ReadFlightState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).ReadFlightState(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_ExchangeGossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).ExchangeGossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_ExchangeGossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).ExchangeGossip(ctx, req.(*GossipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatanodeService_ServiceDesc is the grpc.ServiceDesc for DatanodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatanodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datanode.DatanodeService",
	HandlerType: (*DatanodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessUpdate",
			Handler:    _DatanodeService_ProcessUpdate_Handler,
		},
		{
			MethodName: "ReadFlightState",
			Handler:    _DatanodeService_ReadFlightState_Handler,
		},
		{
			MethodName: "ExchangeGossip",
			Handler:    _DatanodeService_ExchangeGossip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datanode.proto",
}
