// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: coordinator.proto

package coordinator

import (
	datanode "aeroDist/proto/datanode"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlightId      string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	SelectedSeat  string                 `protobuf:"bytes,3,opt,name=selected_seat,json=selectedSeat,proto3" json:"selected_seat,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *CheckInRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CheckInRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *CheckInRequest) GetSelectedSeat() string {
	if x != nil {
		return x.SelectedSeat
	}
	return ""
}

func (x *CheckInRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CheckInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedState  *datanode.FlightState  `protobuf:"bytes,3,opt,name=updated_state,json=updatedState,proto3" json:"updated_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	mi := &file_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *CheckInResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckInResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckInResponse) GetUpdatedState() *datanode.FlightState {
	if x != nil {
		return x.UpdatedState
	}
	return nil
}

type GetBoardingPassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlightId      string                 `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardingPassRequest) Reset() {
	*x = GetBoardingPassRequest{}
	mi := &file_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardingPassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardingPassRequest) ProtoMessage() {}

func (x *GetBoardingPassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardingPassRequest.ProtoReflect.Descriptor instead.
func (*GetBoardingPassRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *GetBoardingPassRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetBoardingPassRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

type GetBoardingPassResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BoardingPassState *datanode.FlightState  `protobuf:"bytes,1,opt,name=boarding_pass_state,json=boardingPassState,proto3" json:"boarding_pass_state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetBoardingPassResponse) Reset() {
	*x = GetBoardingPassResponse{}
	mi := &file_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardingPassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardingPassResponse) ProtoMessage() {}

func (x *GetBoardingPassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardingPassResponse.ProtoReflect.Descriptor instead.
func (*GetBoardingPassResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *GetBoardingPassResponse) GetBoardingPassState() *datanode.FlightState {
	if x != nil {
		return x.BoardingPassState
	}
	return nil
}

var File_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x11coordinator.proto\x12\vcoordinator\x1a\x0edatanode.proto\"\x8e\x01\n" +
	"\x0eCheckInRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\x12#\n" +
	"\rselected_seat\x18\x03 \x01(\tR\fselectedSeat\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\x81\x01\n" +
	"\x0fCheckInResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\rupdated_state\x18\x03 \x01(\v2\x15.datanode.FlightStateR\fupdatedState\"R\n" +
	"\x16GetBoardingPassRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tflight_id\x18\x02 \x01(\tR\bflightId\"`\n" +
	"\x17GetBoardingPassResponse\x12E\n" +
	"\x13boarding_pass_state\x18\x01 \x01(\v2\x15.datanode.FlightStateR\x11boardingPassState2\xb8\x01\n" +
	"\x12CoordinatorService\x12D\n" +
	"\aCheckIn\x12\x1b.coordinator.CheckInRequest\x1a\x1c.coordinator.CheckInResponse\x12\\\n" +
	"\x0fGetBoardingPass\x12#.coordinator.GetBoardingPassRequest\x1a$.coordinator.GetBoardingPassResponseB\x1cZ\x1aaeroDist/proto/coordinatorb\x06proto3"

var (
	file_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_proto_rawDescData []byte
)

func file_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)))
	})
	return file_coordinator_proto_rawDescData
}

var file_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_coordinator_proto_goTypes = []any{
	(*CheckInRequest)(nil),          // 0: coordinator.CheckInRequest
	(*CheckInResponse)(nil),         // 1: coordinator.CheckInResponse
	(*GetBoardingPassRequest)(nil),  // 2: coordinator.GetBoardingPassRequest
	(*GetBoardingPassResponse)(nil), // 3: coordinator.GetBoardingPassResponse
	(*datanode.FlightState)(nil),    // 4: datanode.FlightState
}
var file_coordinator_proto_depIdxs = []int32{
	4, // 0: coordinator.CheckInResponse.updated_state:type_name -> datanode.FlightState
	4, // 1: coordinator.GetBoardingPassResponse.boarding_pass_state:type_name -> datanode.FlightState
	0, // 2: coordinator.CoordinatorService.CheckIn:input_type -> coordinator.CheckInRequest
	2, // 3: coordinator.CoordinatorService.GetBoardingPass:input_type -> coordinator.GetBoardingPassRequest
	1, // 4: coordinator.CoordinatorService.CheckIn:output_type -> coordinator.CheckInResponse
	3, // 5: coordinator.CoordinatorService.GetBoardingPass:output_type -> coordinator.GetBoardingPassResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coordinator_proto_init() }
func file_coordinator_proto_init() {
	if File_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_depIdxs,
		MessageInfos:      file_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_proto = out.File
	file_coordinator_proto_goTypes = nil
	file_coordinator_proto_depIdxs = nil
}
